version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - apis-network
    restart: unless-stopped    

  postgres:
    image: postgres
    container_name: "postgres"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - apis-network
    restart: unless-stopped
  users-api:
    image: users-api-image
    container_name: "users-api"
    expose:
      - "8080"
    ports:
      - 5154:8080
    networks:
      - apis-network
    build:
      context: ../../users-service
      dockerfile: ./src/Users.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=development
    depends_on:
      - rabbitmq

  products-api:
    image: products-api-image
    container_name: "products-api"
    expose:
      - "8080"
    ports:
      - 5155:8080
    networks:
      - apis-network
    build:
      context: ../../products-service
      dockerfile: ./src/Products.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=development
    depends_on:
      - rabbitmq

  orders-api:
    image: orders-api-image
    container_name: "orders-api"
    expose:
      - "8080"
    ports:
      - 5156:8080
    networks:
      - apis-network
    build:
      context: ../../orders-service
      dockerfile: ./src/Orders.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=development
    depends_on:
      - rabbitmq

networks:
  apis-network:
    driver: bridge